word_list = [
    "Sholay",
    "Dilwale Dulhania Le Jayenge",
    "3 Idiots",
    "Kabhi Khushi Kabhie Gham",
    "Lagaan",
    "Mughal-e-Azam",
    "Zindagi Na Milegi Dobara",
    "Chak De! India",
    "Dangal",
    "P.K.",
    "Bajrangi Bhaijaan",
    "Baahubali: The Beginning",
    "Baahubali: The Conclusion",
    "My Name is Khan",
    "Kal Ho Naa Ho",
    "Gully Boy",
    "Queen",
    "Barfi!",
    "Rang De Basanti",
    "Taare Zameen Par",
    "Padmaavat",
    "Bajirao Mastani",
    "Om Shanti Om",
    "Swades",
    "Jab We Met",
    "Yeh Jawaani Hai Deewani",
    "Dhoom 3",
    "Koi... Mil Gaya",
    "Krrish",
    "Krrish 3",
    "Don",
    "Don 2",
    "Kabir Singh",
    "Stree",
    "Andhadhun",
    "Badhai Ho",
    "Article 15",
    "Raazi",
    "Gully Boy",
    "War",
    "Uri: The Surgical Strike",
    "Bahubali",
    "Tanhaji",
    "Golmaal",
    "Golmaal Returns",
    "Housefull",
    "Housefull 2",
    "Housefull 3",
    "Welcome",
    "Welcome Back"
]
